services:
  - type: web
    name: meal-photo-api
    env: python
    pythonVersion: 3.10.13
    buildCommand: |
      rm -rf .venv
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
